### ISSUE TITLE
[Bug] Breaking bricks doesn't reset beams

### ISSUE THREAD

**Issue by QwertymanO07** [HugoBDesigner/Mari0-Community-Edition#50]
Test for funnels, lasers, and lightbridges.  If the player breaks a brick that's in the path of such a beam, it'll simply stop in midair instead of adapting.

**Comment by WillWare** [comment]
Beams do update when portals are shot, but not every frame to save on processing.

Fixing this bug *could* be as easy as updating the beams when a brick is broken, but then we'd be ignoring animated tiles. That might be for the best, since it would be ridiculous to update each time a frame changes on those.

**Comment by QwertymanO07** [comment]
Fixed, though not for animated tiles.
